### ISSUE TITLE
Provide action for flutter-symbols

### ISSUE THREAD

**Issue by aebrahim** [DataDog/datadog-ci#1202]
### Feature request description

It is not clear what the best mechanism is to execute `flutter-symbols` in GitHub actions. I am currently doing this

```
      - id: upload-symbols
        env:
          DATADOG_SITE: <mysite>.datadoghq.com
          DATADOG_API_KEY: <mykey>
        run: >-
          npx @datadog/datadog-ci flutter-symbols upload
          --dart-symbols-location=mySymbolsLocation
          --flavor=myFlavor
          --service-name=com.myCompany.myService
          --version=myVersion
          --android-mapping-location=myLocationmapping.txt
```

This isn't ideal though; for one, build dependencies won't be efficiently cached, and I can't easily pin a version in a way that dependabot will keep up to date for me.

### Solution

It would be great if there was a GitHub action that could do this in a more native way, just like in [DataDog/upload-dsyms-github-action](https://github.com/DataDog/upload-dsyms-github-action)

For example:
```
      - id: upload-symbols
        uses: DataDog/upload-flutter-github-action@v2
        with:
          api_key: <mykey>
          site: us3
          dart-symbols: mySymbolsLocation
          flavor: myFlavor
          serviceName: com.myCompany.myService
          version: myVersion
          android-mapping-location: myLocationMapping.txt
```

### Command

flutter-symbols
