### ISSUE TITLE
We are not pulling junits from nested folders for multi module setup

### ISSUE THREAD

**Issue by vivekkothari** [DataDog/datadog-ci#1304]
### Bug description

When I configure the step as follows,
```
    - name: Upload test results to Datadog
      if: ${{ always() && github.actor != 'dependabot[bot]' }}
      continue-on-error: true
      uses: datadog/junit-upload-github-action@v1
      with:
        api-key: ${{ inputs.datadog-api-key }}
        service: mloop-backend
        env: ci
        files: '**/test-results/**/*.xml'
```
It is not traversing nested paths and fetching the reports from nested path.

### Describe what you expected

Github Action like [EnricoMi/publish-unit-test-result-action](https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#configuration) handle relative paths really well. Would expect this to also work with these paths.

### Command

None
