### ISSUE TITLE
--git-repository-url ignored ?

### ISSUE THREAD

**Issue by rrey** [DataDog/datadog-ci#1498]
### Bug description

Using the [datadog junit upload action](https://github.com/DataDog/junit-upload-github-action), the `--git-repository-url` provided through extra-args is not changing the way the git metadata are retrieved and seems to always retrieve the data from the local git repo.

Example ; by specifying `--git-repository-url git@github.com/<myorg>/<myrepo>.git#<commi-sha>`
I would expect that the tag `git.repository.name` visible in the tests tags would be `<myorg>/<myrepo>` but it is the local repository instead.

### Describe what you expected

The `git` tag content visible in datadog shows the metadata for the repository specified in `--git-repository-url `.

### Steps to reproduce the issue

From a repository call the github action to upload a report with the extra-args providing the `--git-repository-url`:

```
      - name: Send integration test report to Datadog Test Visibility
        if: always()
        uses: datadog/junit-upload-github-action@c4b57b587ae0e3ed618a1f0e7a7d260cfde53032 # v1.4.0 (use commit hash for codacy compliance)
        with:
          api_key: ${{ env.DATADOG_API_KEY }}
          service: dome-service
          files: report.xml
          env: testing
          extra-args: --git-repository-url git@github.com/<some-org>/<some-other-repo>.git#<some-sha>
```

Example of command execution visible in my github actions logs:
``` 
 npx @datadog/datadog-ci@latest junit upload \
    --service example \
    --logs \
    --max-concurrency 20 \
    --xpath-tag test.source.file=/testcase/../@name --git-repository-url git@github.com/<myorg>/<myrepo>.git#<commi-sha> \
    report.xml
```

### Additional context

Github action 1.4.0

### Command

junit
