### ISSUE TITLE
Incorrect exit code when running `datadog-ci git-metadata upload`

### ISSUE THREAD

**Issue by dreinhardt-terminus** [DataDog/datadog-ci#426]
**Describe what happened**
When running the `datadog-ci git-metadata upload` command it errors out but the exit code is still `0`.

**Steps to reproduce the issue:**
* Run the below code so that it errors out (I ran it before checking out the repo as part of a github actions workflow).

```
datadog-ci git-metadata upload
echo "Exited with '$?'
```

**Expected behaviour:**
On errors exit code should be 1.

**Actual behaviour:**
Exit code is 0 even on errors.

**Additional context**
 - ubuntu-latest

**Code Example**

```yaml
env:
  DD_CI: yarn global add @datadog/datadog-ci
  DD_GIT_METADATA: |
    datadog-ci git-metadata upload
    echo "Exited with '$?'"

jobs:
  example:
    name: example
    runs-on: ubuntu-latest
    steps:
    - name: Install Datadog CI
      run: ${{ env.DD_CI }}
    - name: Upload Git MetaData to Datadog
      run: ${{ env.DD_GIT_METADATA }}
```
![image](https://user-images.githubusercontent.com/85892019/141171547-ed002f89-4e88-4eea-9acc-90c211053e01.png)
