### ISSUE TITLE
Unable to override `failOnMissingTests` through config file when using Github Action

### ISSUE THREAD

**Issue by kevcao-certik** [DataDog/datadog-ci#663]
**Describe what happened**
Using the Datadog Synthetics CI GitHub Action, I am unable to set `failOnMissingTests` to `false` and the workflow still fails when no tests are found.

**Steps to reproduce the issue:**
- Create a simple GitHub `.yml` workflow file with the following contents:
```yml
name: Run Datadog Synthetics Tests
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Synthetics Config
        run: |
          echo '{ 
            "failOnMissingTests": false,
            "global": {,
              "startUrl": "<START-URL-HERE>",
              "locations": ["aws:us-east-1"]
            }
          }' > synthetics.json
      - name: Run Datadog Synthetics Tests
        uses: DataDog/synthetics-ci-github-action@v0.6.0
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          app_key: ${{ secrets.DD_APP_KEY }}
          test_search_query: 'tag:<non-existent-tag>'
          config_path: "./synthetics.json"
```

**Expected behaviour:**
No tests should be run, but workflow should not fail.

**Actual behaviour:**
Workflow fails with error:
```
| No test to run.
[Run Datadog Synthetics Tests/run-tests]   ❗  ::error::Running Datadog Synthetics tests failed.
[Run Datadog Synthetics Tests/run-tests]   ❌  Failure - Main Run Datadog Synthetics Tests
[Run Datadog Synthetics Tests/run-tests] exitcode '1': failure
[Run Datadog Synthetics Tests/run-tests] 🏁  Job failed
```
