### ISSUE TITLE
Git Metadata upload for Azure DevOps

### ISSUE THREAD

**Issue by philipwolfe** [DataDog/datadog-ci#850]
### Feature request description

There should be an easy way to upload metadata from the Azure DevOps Datadog CI task.  It looks like all the task can do at the moment is run tests.

### Solution

There should be an option in the task to run the metadata upload command.

### Additional context

I am following these instructions.
![image](https://user-images.githubusercontent.com/61720289/233438142-09708915-308e-400a-bcd4-35a670bca97a.png)

The description of the task says *Use Datadog CI as part of your Azure pipelines*.  But it looks like it can only do tests.
![image](https://user-images.githubusercontent.com/61720289/233438390-eb39a2e2-9498-4d52-aa47-0a4a1957e79a.png)

I am going to try to force it somehow with a combination of running *no* tests and then using powershell to take advantage of the previously installed task.

```yaml
- task: SyntheticsRunTests@0
  inputs:
    authenticationType: 'connectedService'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'datadog-ci git-metadata upload'
```

### Command

git-metadata
